'use client';

import { CompanyProvider } from '@/states/providers/CompanyProvider';
import JWTProvider from '@/states/providers/JWTProvider';
import ModalProvider from '@/states/providers/ModalProvider';
import UserProvider from '@/states/providers/UserProvider';
import React, { useEffect, useState } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

//const inter = Inter({subsets: ['latin']});
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setTheme] = useState('light');
  

  useEffect(() => {
    const darkMode = localStorage.getItem('darkMode') === 'true';
    setTheme(darkMode ? 'dark' : 'light');
  }, []);

  return (
    <html lang='en' className={theme}>
      <body>
        <ModalProvider>
          <JWTProvider>
            <CompanyProvider>
              <UserProvider>
                {children}
                <ToastContainer />
              </UserProvider>
            </CompanyProvider>
          </JWTProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
